/**
 * 内置物品种子（只读 source="builtin"）——unturned.wiki.gg 采集的 vanilla 常用物品。
 *
 * 采集来源：unturned.wiki.gg MediaWiki API——Category:Items 子类逐物品页 infobox 的
 * Internal ID（= Loadout 命令的 ItemID）。采集脚本见会话 scratch。
 * 权威校验：ID 与 U3-SDK 交叉核验吻合（PlayerInventory.cs SKILLSETS_CLIENT 全对上）。
 *
 * name  = wiki 英文源名（权威）
 * label = 中文显示名（仅前端 UI 显示，不进 Commands.dat）
 * 未译项 label 缺省 → 前端回落显示 name。
 */
export const BUILTIN_ITEMS: ReadonlyArray<{ id: number; name: string; label?: string }> = [
  { id: 2, name: "Work Jeans", label: "工装牛仔裤" },
  { id: 4, name: "Eaglefire", label: "鹰火步枪" },
  { id: 6, name: "Military Magazine", label: "军用弹匣" },
  { id: 10, name: "Police Vest", label: "警用背心" },
  { id: 13, name: "Canned Beans", label: "罐装豆子" },
  { id: 14, name: "Bottled Water", label: "瓶装水" },
  { id: 15, name: "Medkit", label: "医疗包" },
  { id: 16, name: "Camp Axe", label: "露营斧" },
  { id: 17, name: "Military Drum", label: "军用弹鼓" },
  { id: 18, name: "Timberwolf", label: "蒂姆伯狼狙击枪" },
  { id: 20, name: "Timberwolf Magazine", label: "蒂姆伯狼弹匣" },
  { id: 27, name: "Tophat", label: "高顶礼帽" },
  { id: 70, name: "Glue", label: "胶水" },
  { id: 75, name: "Chemicals", label: "化学品" },
  { id: 76, name: "Blowtorch", label: "焊枪" },
  { id: 77, name: "Canned Tomato Soup", label: "罐装番茄汤" },
  { id: 78, name: "Canned Chicken Soup", label: "罐装鸡汤" },
  { id: 79, name: "Canned Tuna", label: "罐装金枪鱼" },
  { id: 80, name: "Canned Cola", label: "罐装可乐" },
  { id: 81, name: "MRE", label: "军用口粮" },
  { id: 82, name: "Chips", label: "薯片" },
  { id: 83, name: "Chocolate Bar", label: "巧克力棒" },
  { id: 84, name: "Candy Bar", label: "糖果棒" },
  { id: 85, name: "Granola Bar", label: "燕麦棒" },
  { id: 86, name: "Energy Bar", label: "能量棒" },
  { id: 87, name: "Canned Pasta", label: "罐装意面" },
  { id: 88, name: "Canned Bacon", label: "罐装培根" },
  { id: 89, name: "Canned Beef", label: "罐装牛肉" },
  { id: 90, name: "Canned Sardines", label: "罐装沙丁鱼" },
  { id: 91, name: "Apple Juice", label: "苹果汁" },
  { id: 92, name: "Grape Juice", label: "葡萄汁" },
  { id: 93, name: "Bottled Energy", label: "瓶装能量饮料" },
  { id: 94, name: "Bottled Coconut", label: "瓶装椰汁" },
  { id: 95, name: "Bandage", label: "绷带" },
  { id: 96, name: "Splint", label: "夹板" },
  { id: 97, name: "1911", label: "柯尔特 1911" },
  { id: 98, name: "1911 Magazine", label: "1911 弹匣" },
  { id: 99, name: "Cobra", label: "眼镜蛇手枪" },
  { id: 100, name: "Cobra Magazine", label: "眼镜蛇弹匣" },
  { id: 101, name: "Schofield", label: "斯科菲尔德左轮" },
  { id: 103, name: "Schofield Clip", label: "斯科菲尔德弹夹" },
  { id: 104, name: "Fire Axe", label: "消防斧" },
  { id: 105, name: "Baseball Bat", label: "棒球棒" },
  { id: 106, name: "Hockey Stick", label: "曲棍球棒" },
  { id: 107, name: "Ace", label: "王牌手枪" },
  { id: 108, name: "Ace Clip", label: "王牌弹夹" },
  { id: 109, name: "Hawkhound", label: "鹰犬步枪" },
  { id: 111, name: "Hawkhound Magazine", label: "鹰犬弹匣" },
  { id: 112, name: "Bluntforce", label: "钝击霰弹枪" },
  { id: 113, name: "12 Gauge Shells", label: "12 号霰弹" },
  { id: 115, name: "Raw Mauve Berries", label: "生紫红浆果" },
  { id: 116, name: "PDW", label: "PDW 冲锋枪" },
  { id: 120, name: "Kitchen Knife", label: "厨房刀" },
  { id: 121, name: "Military Knife", label: "军用匕首" },
  { id: 122, name: "Zubeknakov", label: "祖贝卡科夫步枪" },
  { id: 123, name: "Ranger Magazine", label: "游侠弹匣" },
  { id: 125, name: "Ranger Drum", label: "游侠弹鼓" },
  { id: 126, name: "Nykorev", label: "尼克雷夫机枪" },
  { id: 127, name: "Nykorev Box", label: "尼克雷夫弹箱" },
  { id: 129, name: "Snayperskya", label: "狙击斯卡" },
  { id: 130, name: "Snayperskya Magazine", label: "狙击斯卡弹匣" },
  { id: 132, name: "Dragonfang", label: "龙牙步枪" },
  { id: 133, name: "Dragonfang Box", label: "龙牙弹箱" },
  { id: 135, name: "Golf Club", label: "高尔夫球杆" },
  { id: 136, name: "Sledgehammer", label: "大锤" },
  { id: 137, name: "Butcher Knife", label: "屠夫刀" },
  { id: 138, name: "Hammer", label: "锤子" },
  { id: 139, name: "Pocketknife", label: "折叠小刀" },
  { id: 140, name: "Butterfly Knife", label: "蝴蝶刀" },
  { id: 141, name: "Saw", label: "锯子" },
  { id: 142, name: "Rake", label: "耙子" },
  { id: 207, name: "Outfit Jeans", label: "套装牛仔裤" },
  { id: 208, name: "Cowboy Jeans", label: "牛仔牛仔裤" },
  { id: 209, name: "Cargo Pants", label: "工装裤" },
  { id: 211, name: "Plaid Shirt", label: "格子衬衫" },
  { id: 212, name: "Khaki Pants", label: "卡其裤" },
  { id: 213, name: "Corduroy Pants", label: "灯芯绒裤" },
  { id: 214, name: "Trouser Pants", label: "西裤" },
  { id: 223, name: "Police Top", label: "警服上衣" },
  { id: 224, name: "Police Bottom", label: "警服裤子" },
  { id: 225, name: "Police Cap", label: "警帽" },
  { id: 226, name: "Khaki Shorts", label: "卡其短裤" },
  { id: 227, name: "Cargo Shorts", label: "工装短裤" },
  { id: 228, name: "Corduroy Shorts", label: "灯芯绒短裤" },
  { id: 229, name: "Trouser Shorts", label: "西装短裤" },
  { id: 230, name: "Chef Top", label: "厨师上衣" },
  { id: 231, name: "Chef Bottom", label: "厨师裤" },
  { id: 232, name: "Construction Top", label: "建筑工上衣" },
  { id: 233, name: "Firefighter Top", label: "消防员上衣" },
  { id: 234, name: "Firefighter Bottom", label: "消防员裤" },
  { id: 239, name: "Chef Hat", label: "厨师帽" },
  { id: 240, name: "Construction Helmet", label: "建筑安全帽" },
  { id: 241, name: "Firefighter Helmet", label: "消防头盔" },
  { id: 242, name: "Farmer Top", label: "农民上衣" },
  { id: 243, name: "Farmer Bottom", label: "农民裤" },
  { id: 244, name: "Farmer Hat", label: "农民帽" },
  { id: 254, name: "Fragmentation Grenade", label: "破片手雷" },
  { id: 269, name: "Vaccine", label: "疫苗" },
  { id: 270, name: "Raw Amber Berries", label: "生琥珀浆果" },
  { id: 271, name: "Raw Indigo Berries", label: "生靛蓝浆果" },
  { id: 272, name: "Raw Jade Berries", label: "生翡翠浆果" },
  { id: 273, name: "Raw Russet Berries", label: "生赤褐浆果" },
  { id: 274, name: "Raw Teal Berries", label: "生青绿浆果" },
  { id: 275, name: "Raw Vermillion Berries", label: "生朱红浆果" },
  { id: 276, name: "Flashlight", label: "手电筒" },
  { id: 277, name: "Carjack", label: "千斤顶" },
  { id: 297, name: "Grizzly", label: "灰熊狙击枪" },
  { id: 298, name: "Grizzly Magazine", label: "灰熊弹匣" },
  { id: 300, name: "Shadowstalker", label: "影猎手枪" },
  { id: 301, name: "Rail", label: "轨道弩" },
  { id: 303, name: "Prisoner Top", label: "囚犯上衣" },
  { id: 304, name: "Prisoner Bottom", label: "囚犯裤" },
  { id: 305, name: "RCMP Bottom", label: "皇家骑警裤" },
  { id: 306, name: "RCMP Top", label: "皇家骑警上衣" },
  { id: 311, name: "Medic Top", label: "医生上衣" },
  { id: 312, name: "Medic Bottom", label: "医生裤" },
  { id: 313, name: "RCMP Hat", label: "皇家骑警帽" },
  { id: 314, name: "Grocer Top", label: "杂货店主上衣" },
  { id: 315, name: "Grocer Bottom", label: "杂货店主裤" },
  { id: 329, name: "Carrot", label: "胡萝卜" },
  { id: 334, name: "Military Nightvision", label: "军用夜视仪" },
  { id: 335, name: "Corn", label: "玉米" },
  { id: 338, name: "Lettuce", label: "生菜" },
  { id: 340, name: "Tomato", label: "番茄" },
  { id: 342, name: "Potato", label: "土豆" },
  { id: 344, name: "Wheat", label: "小麦" },
  { id: 346, name: "Crossbow", label: "十字弩" },
  { id: 347, name: "Arrow", label: "箭矢" },
  { id: 348, name: "Maple Arrow", label: "枫木箭" },
  { id: 351, name: "Birch Arrow", label: "桦木箭" },
  { id: 352, name: "Pine Arrow", label: "松木箭" },
  { id: 353, name: "Maple Bow", label: "枫木弓" },
  { id: 355, name: "Birch Bow", label: "桦木弓" },
  { id: 356, name: "Pine Bow", label: "松木弓" },
  { id: 357, name: "Compound Bow", label: "复合弓" },
  { id: 363, name: "Maplestrike", label: "枫击步枪" },
  { id: 380, name: "Masterkey", label: "万能钥匙霰弹枪" },
  { id: 381, name: "20 Gauge Shells", label: "20 号霰弹" },
  { id: 387, name: "Adrenaline", label: "肾上腺素" },
  { id: 388, name: "Morphine", label: "吗啡" },
  { id: 389, name: "Antibiotics", label: "抗生素" },
  { id: 390, name: "Painkillers", label: "止痛药" },
  { id: 391, name: "Vitamins", label: "维生素" },
  { id: 392, name: "Purification Tablets", label: "净水药片" },
  { id: 393, name: "Rag", label: "碎布" },
  { id: 394, name: "Dressing", label: "纱布" },
  { id: 395, name: "Bloodbag", label: "血袋" },
  { id: 396, name: "Refined Mauve Berries", label: "精制紫红浆果" },
  { id: 397, name: "Refined Amber Berries", label: "精制琥珀浆果" },
  { id: 398, name: "Refined Indigo Berries", label: "精制靛蓝浆果" },
  { id: 399, name: "Refined Jade Berries", label: "精制翡翠浆果" },
  { id: 400, name: "Refined Russet Berries", label: "精制赤褐浆果" },
  { id: 402, name: "Refined Vermillion Berries", label: "精制朱红浆果" },
  { id: 403, name: "Suturekit", label: "缝合包" },
  { id: 404, name: "Cough Syrup", label: "止咳糖浆" },
  { id: 405, name: "Mechanic Top", label: "机修工上衣" },
  { id: 406, name: "Mechanic Bottom", label: "机修工裤" },
  { id: 407, name: "Engineer Top", label: "工程师上衣" },
  { id: 408, name: "Engineer Bottom", label: "工程师裤" },
  { id: 421, name: "Suit Top", label: "西装上衣" },
  { id: 422, name: "Suit Bottom", label: "西装裤" },
  { id: 423, name: "Engineer Hat", label: "工程师帽" },
  { id: 460, name: "Bread", label: "面包" },
  { id: 461, name: "Tuna Sandwich", label: "金枪鱼三明治" },
  { id: 462, name: "Milk Box", label: "盒装牛奶" },
  { id: 463, name: "Orange Juice", label: "橙汁" },
  { id: 464, name: "Cheese", label: "奶酪" },
  { id: 465, name: "Canned Soda", label: "罐装汽水" },
  { id: 466, name: "Grilled Cheese Sandwich", label: "烤奶酪三明治" },
  { id: 468, name: "Ham Sandwich", label: "火腿三明治" },
  { id: 469, name: "Canned Ham", label: "罐装火腿" },
  { id: 470, name: "Eggs", label: "鸡蛋" },
  { id: 471, name: "Cake", label: "蛋糕" },
  { id: 472, name: "Bottled Cola", label: "瓶装可乐" },
  { id: 473, name: "Bottled Soda", label: "瓶装汽水" },
  { id: 474, name: "Maple Rifle", label: "枫木步枪" },
  { id: 478, name: "Rifle Clip", label: "步枪弹夹" },
  { id: 479, name: "Birch Rifle", label: "桦木步枪" },
  { id: 480, name: "Pine Rifle", label: "松木步枪" },
  { id: 484, name: "Sportshot", label: "运动射手步枪" },
  { id: 485, name: "Sportshot Magazine", label: "运动射手弹匣" },
  { id: 487, name: "Makeshift Bat", label: "自制球棒" },
  { id: 488, name: "Desert Falcon", label: "沙漠隼手枪" },
  { id: 489, name: "Desert Falcon Magazine", label: "沙漠隼弹匣" },
  { id: 490, name: "Chainsaw", label: "电锯" },
  { id: 504, name: "Raw Trout", label: "生鳟鱼" },
  { id: 505, name: "Raw Salmon", label: "生鲑鱼" },
  { id: 509, name: "Fishing Hat", label: "渔夫帽" },
  { id: 510, name: "Fishing Top", label: "渔夫上衣" },
  { id: 511, name: "Fishing Bottom", label: "渔夫裤" },
  { id: 512, name: "Cooked Trout", label: "熟鳟鱼" },
  { id: 513, name: "Cooked Salmon", label: "熟鲑鱼" },
  { id: 514, name: "Raw Venison", label: "生鹿肉" },
  { id: 515, name: "Cooked Venison", label: "熟鹿肉" },
  { id: 517, name: "Leather Top", label: "皮衣上衣" },
  { id: 518, name: "Leather Bottom", label: "皮裤" },
  { id: 519, name: "Rocket Launcher", label: "火箭筒" },
  { id: 520, name: "Rocket", label: "火箭弹" },
  { id: 548, name: "Designer Jeans", label: "名牌牛仔裤" },
  { id: 1000, name: "Matamorez", label: "马塔莫雷兹步枪" },
  { id: 1003, name: "Matamorez Magazine", label: "马塔莫雷兹弹匣" },
  { id: 1005, name: "Matamorez Box", label: "马塔莫雷兹弹箱" },
  { id: 1006, name: "Cobra Box", label: "眼镜蛇弹箱" },
  { id: 1014, name: "Leather Pack", label: "皮革背包" },
  { id: 1015, name: "Biohazard Top", label: "生化服上衣" },
  { id: 1016, name: "Biohazard Bottom", label: "生化服裤" },
  { id: 1017, name: "Biohazard Hood", label: "生化头罩" },
  { id: 1018, name: "Sabertooth", label: "剑齿虎步枪" },
  { id: 1020, name: "Sabertooth Magazine", label: "剑齿虎弹匣" },
  { id: 1021, name: "Avenger", label: "复仇者手枪" },
  { id: 1022, name: "Avenger Magazine", label: "复仇者弹匣" },
  { id: 1023, name: "Baton", label: "警棍" },
  { id: 1024, name: "Peacemaker", label: "和平缔造者步枪" },
  { id: 1026, name: "Peacemaker Magazine", label: "和平缔造者弹匣" },
  { id: 1027, name: "Viper", label: "蝰蛇步枪" },
  { id: 1029, name: "Viper Magazine", label: "蝰蛇弹匣" },
  { id: 1030, name: "Frying Pan", label: "煎锅" },
  { id: 1031, name: "Shovel", label: "铁锹" },
  { id: 1032, name: "Crowbar", label: "撬棍" },
  { id: 1033, name: "Paddle", label: "船桨" },
  { id: 1034, name: "Pitchfork", label: "干草叉" },
  { id: 1035, name: "Machete", label: "砍刀" },
  { id: 1036, name: "Katana", label: "武士刀" },
  { id: 1037, name: "Heartbreaker", label: "伤心人步枪" },
  { id: 1039, name: "Kryzkarek", label: "克雷兹卡雷克手枪" },
  { id: 1040, name: "Kryzkarek Magazine", label: "克雷兹卡雷克弹匣" },
  { id: 1041, name: "Yuri", label: "尤里步枪" },
  { id: 1042, name: "Yuri Magazine", label: "尤里弹匣" },
  { id: 1044, name: "Civilian Nightvision", label: "民用夜视仪" },
  { id: 1046, name: "Pumpkin", label: "南瓜" },
  { id: 1047, name: "Pumpkin Pie", label: "南瓜派" },
  { id: 1048, name: "Hockey Mask", label: "曲棍球面具" },
  { id: 1076, name: "Amber Pie", label: "琥珀派" },
  { id: 1077, name: "Indigo Pie", label: "靛蓝派" },
  { id: 1078, name: "Jade Pie", label: "翡翠派" },
  { id: 1079, name: "Mauve Pie", label: "紫红派" },
  { id: 1080, name: "Russet Pie", label: "赤褐派" },
  { id: 1081, name: "Teal Pie", label: "青绿派" },
  { id: 1082, name: "Vermillion Pie", label: "朱红派" },
  { id: 1100, name: "Sticky Grenade", label: "粘性手雷" },
  { id: 1117, name: "Pork", label: "猪肉" },
  { id: 1118, name: "Bacon", label: "培根" },
  { id: 1120, name: "Raw Beef", label: "生牛肉" },
  { id: 1121, name: "Cooked Beef", label: "熟牛肉" },
  { id: 1129, name: "Heatstim", label: "保温贴" },
  { id: 1132, name: "Snowball", label: "雪球" },
  { id: 1143, name: "Sawed-Off", label: "锯短霰弹枪" },
  { id: 1156, name: "Thief Top", label: "盗贼上衣" },
  { id: 1157, name: "Thief Bottom", label: "盗贼裤" },
  { id: 1159, name: "Maple Syrup", label: "枫糖浆" },
  { id: 1160, name: "Pancake", label: "煎饼" },
  { id: 1161, name: "Waffle", label: "华夫饼" },
  { id: 1162, name: "Dough", label: "面团" },
  { id: 1163, name: "Doughnut", label: "甜甜圈" },
  { id: 1164, name: "Pizza", label: "披萨" },
  { id: 1165, name: "Nailgun", label: "钉枪" },
  { id: 1166, name: "Nailgun Magazine", label: "钉枪弹匣" },
  { id: 1168, name: "Civilian Vest", label: "民用背心" },
  { id: 1169, name: "Spec Ops Vest", label: "特种部队背心" },
  { id: 1170, name: "Spec Ops Rucksack", label: "特种部队背包" },
  { id: 1171, name: "Spec Ops Top", label: "特种部队上衣" },
  { id: 1172, name: "Spec Ops Bottom", label: "特种部队裤" },
  { id: 1173, name: "Makeshift Armor", label: "自制护甲" },
  { id: 1174, name: "Scythe", label: "镰刀" },
  { id: 1177, name: "Military Tracer Magazine", label: "军用曳光弹匣" },
  { id: 1178, name: "Diving Tank", label: "潜水气瓶" },
  { id: 1179, name: "Wetsuit Top", label: "潜水服上衣" },
  { id: 1180, name: "Wetsuit Bottom", label: "潜水服裤" },
  { id: 1181, name: "Snorkel", label: "潜水管" },
  { id: 1198, name: "Pickaxe", label: "镐" },
  { id: 1199, name: "Headlamp", label: "头灯" },
  { id: 1200, name: "Military Fragmentation Magazine", label: "军用破片弹匣" },
  { id: 1209, name: "Explosive Arrow", label: "爆炸箭矢" },
  { id: 1242, name: "Makeshift Grenade", label: "自制手雷" },
  { id: 1270, name: "Gasmask", label: "防毒面具" },
  { id: 1337, name: "Paintball Gun", label: "彩弹枪" },
  { id: 1346, name: "Flashbang", label: "闪光弹" },
  { id: 1347, name: "Raw Minnow", label: "生小鱼" },
  { id: 1348, name: "Cooked Minnow", label: "熟小鱼" },
  { id: 1349, name: "Raw Goldfish", label: "生金鱼" },
  { id: 1350, name: "Cooked Goldfish", label: "熟金鱼" },
  { id: 1351, name: "Raw Bass", label: "生鲈鱼" },
  { id: 1352, name: "Cooked Bass", label: "熟鲈鱼" },
  { id: 1353, name: "Stealy Wheely Automobiley", label: "遥控小车" },
  { id: 1358, name: "Pilot Top", label: "飞行员上衣" },
  { id: 1359, name: "Pilot Cap", label: "飞行员帽" },
  { id: 1360, name: "Teklowvka", label: "捷克罗夫卡手枪" },
  { id: 1361, name: "Teklowvka Magazine", label: "捷克罗夫卡弹匣" },
  { id: 1362, name: "Augewehr", label: "奥格沃尔步枪" },
  { id: 1364, name: "Hell's Fury", label: "地狱之怒" },
  { id: 1365, name: "Hell's Fury Drum", label: "地狱之怒弹鼓" },
  { id: 1366, name: "Vonya", label: "沃尼亚霰弹枪" },
  { id: 1368, name: "Vonya Magazine", label: "沃尼亚弹匣" },
  { id: 1369, name: "Bulldog", label: "斗牛犬步枪" },
  { id: 1371, name: "Bulldog Magazine", label: "斗牛犬弹匣" },
  { id: 1375, name: "Fusilaut", label: "富西洛步枪" },
  { id: 1377, name: "Nightraider", label: "夜袭者步枪" },
  { id: 1379, name: "Calling Card", label: "名片步枪" },
  { id: 1381, name: "Calling Card Magazine", label: "名片弹匣" },
  { id: 1382, name: "Ekho", label: "回声狙击枪" },
  { id: 1384, name: "Ekho Magazine", label: "回声弹匣" },
  { id: 1386, name: "Mafia Tuxedo Top", label: "黑手党燕尾服上衣" },
  { id: 1387, name: "Mafia Tuxedo Bottom", label: "黑手党燕尾服裤" },
  { id: 1390, name: "Pool Cue", label: "台球杆" },
  { id: 1391, name: "Tracksuit Top", label: "运动服上衣" },
  { id: 1392, name: "Tracksuit Bottom", label: "运动裤" },
  { id: 1394, name: "HMG", label: "重机枪" },
  { id: 1395, name: "HMG Box", label: "重机枪弹箱" },
  { id: 1398, name: "Trout Sandwich", label: "鳟鱼三明治" },
  { id: 1399, name: "Salmon Sandwich", label: "鲑鱼三明治" },
  { id: 1400, name: "Minnow Sandwich", label: "小鱼三明治" },
  { id: 1401, name: "Goldfish Sandwich", label: "金鱼三明治" },
  { id: 1402, name: "Venison Sandwich", label: "鹿肉三明治" },
  { id: 1403, name: "Bass Sandwich", label: "鲈鱼三明治" },
  { id: 1405, name: "Cheese Steak Sandwich", label: "芝士牛排三明治" },
  { id: 1419, name: "Coalition Bottom", label: "联合军裤" },
  { id: 1429, name: "Coalition Captain Hat", label: "联合军上尉帽" },
  { id: 1431, name: "Upgraded Cake", label: "升级蛋糕" },
  { id: 1434, name: "Raw Squid", label: "生鱿鱼" },
  { id: 1435, name: "Cooked Squid", label: "熟鱿鱼" },
  { id: 1436, name: "Quadbarrel", label: "四管霰弹枪" },
  { id: 1441, name: "Shadowstalker Mk. II", label: "影猎手枪 II" },
  { id: 1443, name: "Shadowstalker Mk. II Drum", label: "影猎手 II 弹鼓" },
  { id: 1445, name: "Walkie Talkie", label: "对讲机" },
  { id: 1446, name: "Earpiece", label: "耳机" },
  { id: 1447, name: "Scalar", label: "标量步枪" },
  { id: 1449, name: "Scalar Magazine", label: "标量弹匣" },
  { id: 1450, name: "Vehicle Battery", label: "车载电池" },
  { id: 1451, name: "Tire", label: "轮胎" },
  { id: 1453, name: "Split Coconut", label: "剖开椰肉" },
  { id: 1462, name: "Coastguard Top", label: "海警上衣" },
  { id: 1463, name: "Coastguard Bottom", label: "海警裤" },
  { id: 1464, name: "Blindfold", label: "眼罩" },
  { id: 1472, name: "Fighter Pilot Helmet", label: "战斗机飞行员头盔" },
  { id: 1473, name: "Fighter Pilot Top", label: "战斗机飞行员上衣" },
  { id: 1474, name: "Fighter Pilot Bottom", label: "战斗机飞行员裤" },
  { id: 1475, name: "Jackhammer", label: "风镐霰弹枪" },
  { id: 1476, name: "Luger", label: "鲁格手枪" },
  { id: 1477, name: "Maschinengewehr", label: "机枪冲锋枪" },
  { id: 1479, name: "Maschinengewehr Magazine", label: "机枪弹匣" },
  { id: 1480, name: "Determinator", label: "终结者霰弹枪" },
  { id: 1481, name: "Empire", label: "帝国冲锋枪" },
  { id: 1483, name: "Empire Magazine", label: "帝国弹匣" },
  { id: 1484, name: "Devil's Bane", label: "恶魔克星" },
  { id: 1485, name: "Devil's Bane Magazine", label: "恶魔克星弹匣" },
  { id: 1487, name: "Luger Magazine", label: "鲁格弹匣" },
  { id: 1488, name: "Swissgewehr", label: "瑞士步枪" },
  { id: 1490, name: "Swissgewehr Magazine", label: "瑞士弹匣" },
  { id: 1498, name: "Lederhosen Top", label: "皮裤装上衣" },
  { id: 1499, name: "Lederhosen Bottom", label: "皮裤装裤" },
  { id: 1503, name: "Zweihander", label: "双手巨剑" },
  { id: 1504, name: "Pickelhaube", label: "尖顶头盔" },
  { id: 1505, name: "Kaiser Top", label: "皇帝上衣" },
  { id: 1506, name: "Kaiser Bottom", label: "皇帝裤" },
  { id: 1507, name: "Socketwrench", label: "套筒扳手" },
  { id: 1510, name: "Chewing Gum", label: "口香糖" },
  { id: 1520, name: "Impact Grenade", label: "冲击手雷" },
  { id: 1525, name: "Spec Ops Helmet", label: "特种部队头盔" },
  { id: 1693, name: "Snow Shovel", label: "雪铲" },
  { id: 1704, name: "Festive Saw", label: "节日锯子" },
  { id: 1706, name: "Gingerbread Cookie", label: "姜饼曲奇" },
  { id: 1708, name: "Drumstick", label: "鸡腿" },
  { id: 1764, name: "Housing Planner", label: "建造蓝图" },
  { id: 1838, name: "Bounce Grenade", label: "弹跳手雷" },
  { id: 1839, name: "Impact-Absorbing Boots", label: "缓冲靴" },
  { id: 1867, name: "Pike", label: "长矛" },
  { id: 3012, name: "Extended Masterkey (France)", label: "加长万能钥匙（法国）" },
  { id: 3019, name: "Military Vest (France)", label: "军用背心（法国）" },
  { id: 3107, name: "Ghillie Vest (France)", label: "吉利背心（法国）" },
  { id: 4081, name: "Popcorn (California)", label: "爆米花（加州）" },
  { id: 4173, name: "Shadowstalker (California 2)", label: "影猎手枪（加州2）" },
  { id: 6612, name: "Crown (Easter Island)", label: "皇冠（复活节岛）" },
  { id: 25469, name: "Avenger (Buak)", label: "复仇者手枪（Buak）" },
];
