export interface TxtFieldDef {
  key: string;
  label: string;
  type: "bool" | "number" | "string";
  range: string;
  def: string;
  section: string;
  /** 数值字段输入限制（U3-SDK 注释 / 类型约束） */
  min?: number;
  max?: number;
}

export const TXT_FIELD_DEFS: TxtFieldDef[] = [
  { key: "Login_Token", label: "Steam 浏览器登录令牌", type: "string", range: "文本", def: "空", section: "Browser" },
  { key: "Desc_Full", label: "完整描述", type: "string", range: "文本", def: "空", section: "Browser" },
  { key: "Desc_Server_List", label: "列表描述", type: "string", range: "文本", def: "空", section: "Browser" },
  { key: "Icon", label: "图标 URL", type: "string", range: "文本", def: "空", section: "Browser" },
  { key: "Thumbnail", label: "缩略图 URL", type: "string", range: "文本", def: "空", section: "Browser" },
  { key: "VAC_Secure", label: "VAC 反作弊", type: "bool", range: "开关", def: "开", section: "Server" },
  { key: "BattlEye_Secure", label: "BattlEye", type: "bool", range: "开关", def: "开", section: "Server" },
  { key: "Max_Ping_Milliseconds", label: "最大 Ping(ms)", type: "number", range: "数值", def: "750", section: "Server", min: 0 },
  { key: "Enable_Scheduled_Shutdown", label: "定时关机", type: "bool", range: "开关", def: "关", section: "Server" },
  { key: "Enable_Update_Shutdown", label: "更新自动关机", type: "bool", range: "开关", def: "关", section: "Server" },
  { key: "Spawn_Chance", label: "生成倍率", type: "number", range: "0–1", def: "简单0.35/普通0.35/困难0.15", section: "Items", min: 0, max: 1 },
  { key: "Has_Durability", label: "物品耐久", type: "bool", range: "开关", def: "简单关/普通开/困难开", section: "Items" },
  { key: "Despawn_Dropped_Time", label: "掉落消失(s)", type: "number", range: "数值", def: "600", section: "Items", min: 0 },
  { key: "Respawn_Time", label: "重生时间(s)", type: "number", range: "数值", def: "简单50/普通100/困难150", section: "Items", min: 0 },
  { key: "Allow_Shoulder_Camera", label: "肩后视角", type: "bool", range: "开关", def: "开", section: "Gameplay" },
  { key: "Allow_Freeform_Buildables", label: "自由建造", type: "bool", range: "开关", def: "开", section: "Gameplay" },
  { key: "Friendly_Fire", label: "玩家伤害", type: "bool", range: "开关", def: "关", section: "Gameplay" },
  { key: "Can_Suicide", label: "允许自杀", type: "bool", range: "开关", def: "开", section: "Gameplay" },
  { key: "Decay_Time", label: "闲置损坏时间", type: "number", range: "数值（秒）", def: "604800", section: "Vehicles", min: 0 },
  { key: "Decay_Damage_Per_Second", label: "闲置损坏速度", type: "number", range: "数值", def: "0.1", section: "Vehicles", min: 0 },
  { key: "Has_Battery_Chance", label: "带电池概率", type: "number", range: "0–1", def: "简单1 / 普通0.8 / 困难0.25", section: "Vehicles", min: 0, max: 1 },
  { key: "Min_Battery_Charge", label: "电池最小电量", type: "number", range: "0–1", def: "简单0.8 / 普通0.5 / 困难0.1", section: "Vehicles", min: 0, max: 1 },
  { key: "Max_Battery_Charge", label: "电池最大电量", type: "number", range: "0–1", def: "简单1 / 普通0.75 / 困难0.3", section: "Vehicles", min: 0, max: 1 },
  { key: "Has_Tire_Chance", label: "带轮胎概率", type: "number", range: "0–1", def: "简单1 / 普通0.85 / 困难0.7", section: "Vehicles", min: 0, max: 1 },
  { key: "Respawn_Time", label: "消失时间", type: "number", range: "数值（秒）", def: "300", section: "Vehicles", min: 0 },
  { key: "Unlocked_After_Seconds_In_Safezone", label: "安全区自动解锁", type: "number", range: "数值（秒）", def: "3600", section: "Vehicles", min: 0 },
  { key: "Armor_Multiplier", label: "护甲系数", type: "number", range: "数值", def: "1", section: "Vehicles", min: 0 },
  { key: "Child_Explosion_Armor_Multiplier", label: "爆炸物护甲系数", type: "number", range: "数值", def: "1", section: "Vehicles", min: 0 },
  { key: "Gun_Lowcal_Damage_Multiplier", label: "轻武器伤害系数", type: "number", range: "数值", def: "1", section: "Vehicles", min: 0 },
  { key: "Gun_Highcal_Damage_Multiplier", label: "重型武器伤害系数", type: "number", range: "数值", def: "1", section: "Vehicles", min: 0 },
  { key: "Melee_Damage_Multiplier", label: "近战伤害系数", type: "number", range: "数值", def: "1", section: "Vehicles", min: 0 },
  { key: "Melee_Repair_Multiplier", label: "近战修复系数", type: "number", range: "数值", def: "1", section: "Vehicles", min: 0 },
  { key: "Max_Instances_Tiny", label: "迷你图最大数量", type: "number", range: "整数", def: "4", section: "Vehicles", min: 0 },
  { key: "Max_Instances_Small", label: "小型图最大数量", type: "number", range: "整数", def: "8", section: "Vehicles", min: 0 },
  { key: "Max_Instances_Medium", label: "中型图最大数量", type: "number", range: "整数", def: "16", section: "Vehicles", min: 0 },
  { key: "Max_Instances_Large", label: "大型图最大数量", type: "number", range: "整数", def: "32", section: "Vehicles", min: 0 },
  { key: "Max_Instances_Insane", label: "超大图最大数量", type: "number", range: "整数", def: "64", section: "Vehicles", min: 0 },
  { key: "Min_Natural_Vehicles", label: "自然载具下限", type: "number", range: "整数", def: "16", section: "Vehicles", min: 0 },
  { key: "Spawn_Chance", label: "生成概率", type: "number", range: "0–1", def: "简单0.2 / 普通0.25 / 困难0.3", section: "Zombies", min: 0, max: 1 },
  { key: "Loot_Chance", label: "掉落概率", type: "number", range: "0–1", def: "简单0.55 / 普通0.5 / 困难0.3", section: "Zombies", min: 0, max: 1 },
  { key: "Crawler_Chance", label: "爬行者概率", type: "number", range: "0–1", def: "简单0 / 普通0.15 / 困难0.125", section: "Zombies", min: 0, max: 1 },
  { key: "Sprinter_Chance", label: "疾跑者概率", type: "number", range: "0–1", def: "简单0 / 普通0.15 / 困难0.175", section: "Zombies", min: 0, max: 1 },
  { key: "Flanker_Chance", label: "侧翼者概率", type: "number", range: "0–1", def: "简单0 / 普通0.025 / 困难0.05", section: "Zombies", min: 0, max: 1 },
  { key: "Burner_Chance", label: "燃烧者概率", type: "number", range: "0–1", def: "简单0 / 普通0.025 / 困难0.05", section: "Zombies", min: 0, max: 1 },
  { key: "Acid_Chance", label: "酸液者概率", type: "number", range: "0–1", def: "简单0 / 普通0.025 / 困难0.05", section: "Zombies", min: 0, max: 1 },
  { key: "Boss_Electric_Chance", label: "电系首领概率", type: "number", range: "0–1", def: "0", section: "Zombies", min: 0, max: 1 },
  { key: "Boss_Wind_Chance", label: "震地首领概率", type: "number", range: "0–1", def: "0", section: "Zombies", min: 0, max: 1 },
  { key: "Boss_Fire_Chance", label: "喷火首领概率", type: "number", range: "0–1", def: "0", section: "Zombies", min: 0, max: 1 },
  { key: "Spirit_Chance", label: "幽灵概率", type: "number", range: "0–1", def: "0", section: "Zombies", min: 0, max: 1 },
  { key: "DL_Red_Volatile_Chance", label: "红色夜魔概率", type: "number", range: "0–1", def: "0", section: "Zombies", min: 0, max: 1 },
  { key: "DL_Blue_Volatile_Chance", label: "蓝色夜魔概率", type: "number", range: "0–1", def: "0", section: "Zombies", min: 0, max: 1 },
  { key: "Boss_Elver_Stomper_Chance", label: "巨树首领概率", type: "number", range: "0–1", def: "0", section: "Zombies", min: 0, max: 1 },
  { key: "Boss_Kuwait_Chance", label: "科威特首领概率", type: "number", range: "0–1", def: "0", section: "Zombies", min: 0, max: 1 },
  { key: "Respawn_Day_Time", label: "白天重生时间", type: "number", range: "数值（秒）", def: "360", section: "Zombies", min: 0 },
  { key: "Respawn_Night_Time", label: "满月重生时间", type: "number", range: "数值（秒）", def: "30", section: "Zombies", min: 0 },
  { key: "Respawn_Beacon_Time", label: "尸潮信标重生", type: "number", range: "数值（秒）", def: "0", section: "Zombies", min: 0 },
  { key: "Quest_Boss_Respawn_Interval", label: "任务首领重生间隔", type: "number", range: "数值（秒）", def: "600", section: "Zombies", min: 0 },
  { key: "Damage_Multiplier", label: "伤害系数", type: "number", range: "数值", def: "简单0.75 / 普通1 / 困难1.5", section: "Zombies", min: 0 },
  { key: "Armor_Multiplier", label: "护甲系数", type: "number", range: "数值", def: "简单1.25 / 普通1 / 困难0.75", section: "Zombies", min: 0 },
  { key: "Backstab_Multiplier", label: "背刺系数", type: "number", range: "数值", def: "1.25", section: "Zombies", min: 0 },
  { key: "NonHeadshot_Armor_Multiplier", label: "非爆头护甲系数", type: "number", range: "数值", def: "1", section: "Zombies", min: 0 },
  { key: "Beacon_Experience_Multiplier", label: "信标经验系数", type: "number", range: "数值", def: "1", section: "Zombies", min: 0 },
  { key: "Full_Moon_Experience_Multiplier", label: "满月经验系数", type: "number", range: "数值", def: "2", section: "Zombies", min: 0 },
  { key: "Min_Drops", label: "最小掉落", type: "number", range: "整数", def: "1", section: "Zombies", min: 0 },
  { key: "Max_Drops", label: "最大掉落", type: "number", range: "整数", def: "1", section: "Zombies", min: 0 },
  { key: "Min_Mega_Drops", label: "巨型最小掉落", type: "number", range: "整数", def: "5", section: "Zombies", min: 0 },
  { key: "Max_Mega_Drops", label: "巨型最大掉落", type: "number", range: "整数", def: "5", section: "Zombies", min: 0 },
  { key: "Min_Boss_Drops", label: "首领最小掉落", type: "number", range: "整数", def: "8", section: "Zombies", min: 0 },
  { key: "Max_Boss_Drops", label: "首领最大掉落", type: "number", range: "整数", def: "10", section: "Zombies", min: 0 },
  { key: "Slow_Movement", label: "缓慢移动", type: "bool", range: "开关", def: "简单开 / 普通关 / 困难关", section: "Zombies" },
  { key: "Can_Stun", label: "可被眩晕", type: "bool", range: "开关", def: "简单开 / 普通开 / 困难关", section: "Zombies" },
  { key: "Only_Critical_Stuns", label: "仅关键眩晕", type: "bool", range: "开关", def: "简单关 / 普通关 / 困难开", section: "Zombies" },
  { key: "Weapons_Use_Player_Damage", label: "武器用玩家伤害", type: "bool", range: "开关", def: "简单关 / 普通关 / 困难开", section: "Zombies" },
  { key: "Can_Target_Barricades", label: "可攻击路障", type: "bool", range: "开关", def: "开", section: "Zombies" },
  { key: "Can_Target_Structures", label: "可攻击建筑", type: "bool", range: "开关", def: "开", section: "Zombies" },
  { key: "Can_Target_Vehicles", label: "可攻击载具", type: "bool", range: "开关", def: "开", section: "Zombies" },
  { key: "Can_Target_Objects", label: "可攻击世界物件", type: "bool", range: "开关", def: "开", section: "Zombies" },
  { key: "Beacon_Max_Rewards", label: "信标最大奖励", type: "number", range: "整数", def: "0", section: "Zombies", min: 0 },
  { key: "Beacon_Max_Participants", label: "信标最大参与", type: "number", range: "整数", def: "0", section: "Zombies", min: 0 },
  { key: "Beacon_Rewards_Multiplier", label: "信标奖励系数", type: "number", range: "数值", def: "1", section: "Zombies", min: 0 },
  { key: "Respawn_Time", label: "重生时间", type: "number", range: "数值（秒）", def: "180", section: "Animals", min: 0 },
  { key: "Damage_Multiplier", label: "伤害系数", type: "number", range: "数值", def: "简单0.75 / 普通1 / 困难1.5", section: "Animals", min: 0 },
  { key: "Armor_Multiplier", label: "护甲系数", type: "number", range: "数值", def: "简单1.25 / 普通1 / 困难0.75", section: "Animals", min: 0 },
  { key: "Max_Instances_Tiny", label: "迷你图最大数量", type: "number", range: "整数", def: "4", section: "Animals", min: 0 },
  { key: "Max_Instances_Small", label: "小型图最大数量", type: "number", range: "整数", def: "8", section: "Animals", min: 0 },
  { key: "Max_Instances_Medium", label: "中型图最大数量", type: "number", range: "整数", def: "16", section: "Animals", min: 0 },
  { key: "Max_Instances_Large", label: "大型图最大数量", type: "number", range: "整数", def: "32", section: "Animals", min: 0 },
  { key: "Max_Instances_Insane", label: "超大图最大数量", type: "number", range: "整数", def: "64", section: "Animals", min: 0 },
  { key: "Weapons_Use_Player_Damage", label: "武器用玩家伤害", type: "bool", range: "开关", def: "简单关 / 普通关 / 困难开", section: "Animals" },
  { key: "Decay_Time", label: "腐烂时间", type: "number", range: "整数（秒）", def: "604800", section: "Barricades", min: 0 },
  { key: "Armor_Lowtier_Multiplier", label: "低阶护甲系数", type: "number", range: "数值", def: "1", section: "Barricades", min: 0 },
  { key: "Armor_Hightier_Multiplier", label: "高阶护甲系数", type: "number", range: "数值", def: "0.5", section: "Barricades", min: 0 },
  { key: "Gun_Lowcal_Damage_Multiplier", label: "轻武器伤害系数", type: "number", range: "数值", def: "1", section: "Barricades", min: 0 },
  { key: "Gun_Highcal_Damage_Multiplier", label: "重型武器伤害系数", type: "number", range: "数值", def: "1", section: "Barricades", min: 0 },
  { key: "Melee_Damage_Multiplier", label: "近战伤害系数", type: "number", range: "数值", def: "1", section: "Barricades", min: 0 },
  { key: "Melee_Repair_Multiplier", label: "近战修复系数", type: "number", range: "数值", def: "1", section: "Barricades", min: 0 },
  { key: "Allow_Item_Placement_On_Vehicle", label: "允许载具上放置", type: "bool", range: "开关", def: "开", section: "Barricades" },
  { key: "Allow_Trap_Placement_On_Vehicle", label: "允许载具上放陷阱", type: "bool", range: "开关", def: "开", section: "Barricades" },
  { key: "Max_Item_Distance_From_Hull", label: "最大建造距离", type: "number", range: "数值", def: "64", section: "Barricades", min: 0 },
  { key: "Max_Trap_Distance_From_Hull", label: "最大陷阱距离", type: "number", range: "数值", def: "16", section: "Barricades", min: 0 },
  { key: "Decay_Time", label: "腐烂时间", type: "number", range: "整数（秒）", def: "604800", section: "Structures", min: 0 },
  { key: "Armor_Lowtier_Multiplier", label: "低阶护甲系数", type: "number", range: "数值", def: "1", section: "Structures", min: 0 },
  { key: "Armor_Hightier_Multiplier", label: "高阶护甲系数", type: "number", range: "数值", def: "0.5", section: "Structures", min: 0 },
  { key: "Gun_Lowcal_Damage_Multiplier", label: "轻武器伤害系数", type: "number", range: "数值", def: "1", section: "Structures", min: 0 },
  { key: "Gun_Highcal_Damage_Multiplier", label: "重型武器伤害系数", type: "number", range: "数值", def: "1", section: "Structures", min: 0 },
  { key: "Melee_Damage_Multiplier", label: "近战伤害系数", type: "number", range: "数值", def: "1", section: "Structures", min: 0 },
  { key: "Melee_Repair_Multiplier", label: "近战修复系数", type: "number", range: "数值", def: "1", section: "Structures", min: 0 },
  { key: "Health_Default", label: "初始生命", type: "number", range: "0–100", def: "100", section: "Players", min: 0, max: 100 },
  { key: "Health_Regen_Min_Food", label: "回血最低饱食", type: "number", range: "整数", def: "90", section: "Players", min: 0 },
  { key: "Health_Regen_Min_Water", label: "回血最低饮水", type: "number", range: "整数", def: "90", section: "Players", min: 0 },
  { key: "Health_Regen_Ticks", label: "回血速度", type: "number", range: "整数", def: "60", section: "Players", min: 0 },
  { key: "Food_Default", label: "初始饱食", type: "number", range: "0–100", def: "简单100 / 普通100 / 困难85", section: "Players", min: 0, max: 100 },
  { key: "Food_Use_Ticks", label: "饱食消耗速度", type: "number", range: "整数", def: "简单350 / 普通300 / 困难250", section: "Players", min: 0 },
  { key: "Food_Damage_Ticks", label: "饿死速度", type: "number", range: "整数", def: "15", section: "Players", min: 0 },
  { key: "Water_Default", label: "初始饮水", type: "number", range: "0–100", def: "简单100 / 普通100 / 困难85", section: "Players", min: 0, max: 100 },
  { key: "Water_Use_Ticks", label: "饮水消耗速度", type: "number", range: "整数", def: "简单320 / 普通270 / 困难220", section: "Players", min: 0 },
  { key: "Water_Damage_Ticks", label: "渴死速度", type: "number", range: "整数", def: "20", section: "Players", min: 0 },
  { key: "Virus_Default", label: "初始免疫", type: "number", range: "0–100", def: "100", section: "Players", min: 0, max: 100 },
  { key: "Virus_Infect", label: "感染阈值", type: "number", range: "整数", def: "50", section: "Players", min: 0 },
  { key: "Virus_Use_Ticks", label: "免疫消耗速度", type: "number", range: "整数", def: "125", section: "Players", min: 0 },
  { key: "Virus_Damage_Ticks", label: "免疫为零死亡速度", type: "number", range: "整数", def: "25", section: "Players", min: 0 },
  { key: "Leg_Regen_Ticks", label: "断腿愈合速度", type: "number", range: "整数", def: "750", section: "Players", min: 0 },
  { key: "Bleed_Damage_Ticks", label: "流血伤害速度", type: "number", range: "整数", def: "10", section: "Players", min: 0 },
  { key: "Bleed_Regen_Ticks", label: "流血愈合速度", type: "number", range: "整数", def: "750", section: "Players", min: 0 },
  { key: "Armor_Multiplier", label: "护甲系数", type: "number", range: "数值", def: "1", section: "Players", min: 0 },
  { key: "Experience_Multiplier", label: "经验系数", type: "number", range: "数值", def: "简单1.5 / 普通1 / 困难1.5", section: "Players", min: 0 },
  { key: "Detect_Radius_Multiplier", label: "侦测半径系数", type: "number", range: "数值", def: "简单0.5 / 普通1 / 困难1.25", section: "Players", min: 0 },
  { key: "Ray_Aggressor_Distance", label: "攻击判定距离", type: "number", range: "数值", def: "8", section: "Players", min: 0 },
  { key: "Lose_Skills_PvP", label: "玩家击杀保留技能", type: "number", range: "0–1", def: "1", section: "Players", min: 0, max: 1 },
  { key: "Lose_Skills_PvE", label: "环境击杀保留技能", type: "number", range: "0–1", def: "1", section: "Players", min: 0, max: 1 },
  { key: "Lose_Skill_Levels_PvP", label: "玩家击杀扣技能级", type: "number", range: "整数", def: "简单0 / 普通1 / 困难2", section: "Players", min: 0 },
  { key: "Lose_Skill_Levels_PvE", label: "环境击杀扣技能级", type: "number", range: "整数", def: "简单0 / 普通1 / 困难2", section: "Players", min: 0 },
  { key: "Lose_Experience_PvP", label: "玩家击杀保留经验", type: "number", range: "0–1", def: "0.5", section: "Players", min: 0, max: 1 },
  { key: "Lose_Experience_PvE", label: "环境击杀保留经验", type: "number", range: "0–1", def: "0.5", section: "Players", min: 0, max: 1 },
  { key: "Skill_Cost_Multiplier", label: "技能花费系数", type: "number", range: "数值", def: "1", section: "Players", min: 0 },
  { key: "Lose_Items_PvP", label: "玩家击杀掉物概率", type: "number", range: "0–1", def: "1", section: "Players", min: 0, max: 1 },
  { key: "Lose_Items_PvE", label: "环境击杀掉物概率", type: "number", range: "0–1", def: "1", section: "Players", min: 0, max: 1 },
  { key: "Lose_Clothes_PvP", label: "玩家击杀掉衣服", type: "bool", range: "开关", def: "开", section: "Players" },
  { key: "Lose_Clothes_PvE", label: "环境击杀掉衣服", type: "bool", range: "开关", def: "开", section: "Players" },
  { key: "Lose_Weapons_PvP", label: "玩家击杀掉武器", type: "bool", range: "开关", def: "开", section: "Players" },
  { key: "Lose_Weapons_PvE", label: "环境击杀掉武器", type: "bool", range: "开关", def: "开", section: "Players" },
  { key: "Can_Hurt_Legs", label: "坠伤", type: "bool", range: "开关", def: "开", section: "Players" },
  { key: "Can_Break_Legs", label: "坠断腿", type: "bool", range: "开关", def: "简单关 / 普通开 / 困难开", section: "Players" },
  { key: "Can_Fix_Legs", label: "断腿自愈", type: "bool", range: "开关", def: "简单开 / 普通开 / 困难关", section: "Players" },
  { key: "Can_Start_Bleeding", label: "可流血", type: "bool", range: "开关", def: "简单关 / 普通开 / 困难开", section: "Players" },
  { key: "Can_Stop_Bleeding", label: "流血自愈", type: "bool", range: "开关", def: "简单开 / 普通开 / 困难关", section: "Players" },
  { key: "Spawn_With_Max_Skills", label: "满级技能出生", type: "bool", range: "开关", def: "关", section: "Players" },
  { key: "Spawn_With_Stamina_Skills", label: "满级耐力技能出生", type: "bool", range: "开关", def: "关", section: "Players" },
  { key: "Skillset_Reduces_Skill_Cost", label: "职业技能半价", type: "bool", range: "开关", def: "开", section: "Players" },
  { key: "Skillset_Prevents_Skill_Loss", label: "职业技能不掉级", type: "bool", range: "开关", def: "开", section: "Players" },
  { key: "Prevent_Level_Skill_Overrides", label: "禁止等级覆盖技能", type: "bool", range: "开关", def: "关", section: "Players" },
  { key: "Allow_Instakill_Headshots", label: "狙击爆头必杀", type: "bool", range: "开关", def: "简单关 / 普通关 / 困难开", section: "Players" },
  { key: "Allow_Per_Character_Saves", label: "按角色存档", type: "bool", range: "开关", def: "关", section: "Players" },
  { key: "Enable_Terrain_Color_Kick", label: "地形色踢出", type: "bool", range: "开关", def: "开", section: "Players" },
  { key: "Binary_State_Reset_Multiplier", label: "电器关闭系数", type: "number", range: "数值", def: "1", section: "Objects", min: 0 },
  { key: "Fuel_Reset_Multiplier", label: "燃油补充系数", type: "number", range: "数值", def: "1", section: "Objects", min: 0 },
  { key: "Water_Reset_Multiplier", label: "水源补充系数", type: "number", range: "数值", def: "1", section: "Objects", min: 0 },
  { key: "Resource_Reset_Multiplier", label: "资源生长系数", type: "number", range: "数值", def: "1", section: "Objects", min: 0 },
  { key: "Resource_Drops_Multiplier", label: "资源掉落系数", type: "number", range: "数值", def: "1", section: "Objects", min: 0 },
  { key: "Rubble_Reset_Multiplier", label: "可毁物修复系数", type: "number", range: "数值", def: "1", section: "Objects", min: 0 },
  { key: "Allow_Holiday_Drops", label: "节日掉落", type: "bool", range: "开关", def: "开", section: "Objects" },
  { key: "Items_Obstruct_Tree_Respawns", label: "阻挡树重生", type: "bool", range: "开关", def: "开", section: "Objects" },
  { key: "Rain_Frequency_Min", label: "雨最小间隔", type: "number", range: "数值（天）", def: "2.3", section: "Events", min: 0 },
  { key: "Rain_Frequency_Max", label: "雨最大间隔", type: "number", range: "数值（天）", def: "5.6", section: "Events", min: 0 },
  { key: "Rain_Duration_Min", label: "雨最短时长", type: "number", range: "数值（天）", def: "0.05", section: "Events", min: 0 },
  { key: "Rain_Duration_Max", label: "雨最长时长", type: "number", range: "数值（天）", def: "0.15", section: "Events", min: 0 },
  { key: "Snow_Frequency_Min", label: "雪最小间隔", type: "number", range: "数值（天）", def: "1.3", section: "Events", min: 0 },
  { key: "Snow_Frequency_Max", label: "雪最大间隔", type: "number", range: "数值（天）", def: "4.6", section: "Events", min: 0 },
  { key: "Snow_Duration_Min", label: "雪最短时长", type: "number", range: "数值（天）", def: "0.2", section: "Events", min: 0 },
  { key: "Snow_Duration_Max", label: "雪最长时长", type: "number", range: "数值（天）", def: "0.5", section: "Events", min: 0 },
  { key: "Weather_Frequency_Multiplier", label: "天气频率系数", type: "number", range: "数值", def: "1", section: "Events", min: 0 },
  { key: "Weather_Duration_Multiplier", label: "天气时长系数", type: "number", range: "数值", def: "1", section: "Events", min: 0 },
  { key: "Airdrop_Frequency_Min", label: "空投最小间隔", type: "number", range: "数值（天）", def: "0.8", section: "Events", min: 0 },
  { key: "Airdrop_Frequency_Max", label: "空投最大间隔", type: "number", range: "数值（天）", def: "6.5", section: "Events", min: 0 },
  { key: "Airdrop_Speed", label: "空投飞机速度", type: "number", range: "数值（米/秒）", def: "128", section: "Events", min: 0 },
  { key: "Airdrop_Force", label: "空投浮力", type: "number", range: "数值", def: "9.5", section: "Events", min: 0 },
  { key: "Arena_Min_Players", label: "竞技场最小人数", type: "number", range: "整数", def: "2", section: "Events", min: 0 },
  { key: "Arena_Compactor_Damage", label: "圈外基础伤害", type: "number", range: "整数", def: "9", section: "Events", min: 0 },
  { key: "Arena_Compactor_Extra_Damage_Per_Second", label: "圈外递增伤害", type: "number", range: "数值", def: "1", section: "Events", min: 0 },
  { key: "Arena_Clear_Timer", label: "传送前等待", type: "number", range: "整数（秒）", def: "5", section: "Events", min: 0 },
  { key: "Arena_Finale_Timer", label: "决赛等待", type: "number", range: "整数（秒）", def: "10", section: "Events", min: 0 },
  { key: "Arena_Restart_Timer", label: "中场休息", type: "number", range: "整数（秒）", def: "15", section: "Events", min: 0 },
  { key: "Arena_Compactor_Delay_Timer", label: "首圈延迟", type: "number", range: "整数（秒）", def: "1", section: "Events", min: 0 },
  { key: "Arena_Compactor_Pause_Timer", label: "圈收缩暂停", type: "number", range: "整数（秒）", def: "5", section: "Events", min: 0 },
  { key: "Use_Airdrops", label: "启用空投", type: "bool", range: "开关", def: "开", section: "Events" },
  { key: "Arena_Use_Compactor_Pause", label: "圈内多圈", type: "bool", range: "开关", def: "开", section: "Events" },
  { key: "Arena_Compactor_Speed_Tiny", label: "迷你图缩圈速度", type: "number", range: "数值（米/秒）", def: "0.5", section: "Events", min: 0 },
  { key: "Arena_Compactor_Speed_Small", label: "小型图缩圈速度", type: "number", range: "数值（米/秒）", def: "1.5", section: "Events", min: 0 },
  { key: "Arena_Compactor_Speed_Medium", label: "中型图缩圈速度", type: "number", range: "数值（米/秒）", def: "3", section: "Events", min: 0 },
  { key: "Arena_Compactor_Speed_Large", label: "大型图缩圈速度", type: "number", range: "数值（米/秒）", def: "4.5", section: "Events", min: 0 },
  { key: "Arena_Compactor_Speed_Insane", label: "超大图缩圈速度", type: "number", range: "数值（米/秒）", def: "6", section: "Events", min: 0 },
  { key: "Arena_Compactor_Shrink_Factor", label: "缩圈保留系数", type: "number", range: "0–1", def: "0.5", section: "Events", min: 0, max: 1 },
  { key: "Allow_Server_Messages", label: "服务端广播", type: "bool", range: "开关", def: "关", section: "UnityEvents" },
  { key: "Allow_Server_Commands", label: "服务端命令", type: "bool", range: "开关", def: "关", section: "UnityEvents" },
  { key: "Allow_Client_Messages", label: "客户端广播", type: "bool", range: "开关", def: "关", section: "UnityEvents" },
  { key: "Allow_Client_Commands", label: "客户端命令", type: "bool", range: "开关", def: "关", section: "UnityEvents" },
];
